# Generated by Django 4.0.5 on 2022-06-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecordReading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='text',
            field=models.TextField(default='感想を入力', verbose_name='感想'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='end_date',
            field=models.DateField(verbose_name='読書終了日'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='start_date',
            field=models.DateField(verbose_name='読書開始日'),
        ),
    ]
